title: 大象小象
name: 大象小象

permalink: /blog/:year/:month/:day/:title

# Pagination
paginate: 15

# Markdown Processors
markdown: kramdown
kramdown:
  input: GFM

# Code Highlighter
highlighter: rouge
highlight:
line_number: true

# Website favicon
favicon: /assets/images/favicon.ico

# Plugins
plugins:
  - jekyll-sitemap
  - jemoji
  - jekyll-feed

# Atom feed
feed:
  path: atom.xml